"""
Django settings for z_app_tecnoshop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i8ulv)cjy6l=*e6p^5sa&@+6of8pnr+@i=2k4v-vyqigcp#81u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # apps de django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps
    'pages',
    'catalog',
    'accounts',
    'cart',
    'orders',
    'payments',

    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # API
    'rest_framework',

    # Import Export
    "import_export",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # requerido por django-allauth
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'z_app_tecnoshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'z_app_tecnoshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # login normal de Django
    "allauth.account.auth_backends.AuthenticationBackend",  # login de allauth
]

SITE_ID = 1

LOGIN_REDIRECT_URL = "/"   # a dónde enviar después de login
LOGOUT_REDIRECT_URL = "/"  # a dónde enviar después de logout

# Métodos de login
ACCOUNT_LOGIN_METHODS = {'email'}  # o solo 'email' si quieres

# Campos requeridos en signup
ACCOUNT_SIGNUP_FIELDS = [
    'username*',   # el asterisco indica que es obligatorio
    'email*',
    'password1*',
    'password2*',
    'first_name',  # opcional si quieres que sea obligatorio, agrega *
    'last_name',   # opcional si quieres que sea obligatorio, agrega *
]

ACCOUNT_EMAIL_VERIFICATION = 'none'  # 'mandatory' si quieres verificar correo

# Idioma predeterminado
LANGUAGE_CODE = 'es'  

# Zona horaria de tu región
TIME_ZONE = 'America/Lima'  # ajusta según tu ubicación

LOGIN_URL = 'account_login'


# Prueba
ALLOWED_HOSTS = ['*']
